
using script reflection

struct Accuracy:
    order: integer = 7
    pre_hit: function = function "pre_hit"

local function add(stat: Stat struct) -> Accuracy struct:
    return Accuracy struct instance

local function pre_hit(ctx: CombatContext struct, stat: Stat struct):
    if chance of (100 - {_stat}->current)%:
        set {_ctx}->miss to true

local function load():
    save_component("stat:accuracy", a_stat_field(StatFieldBuilder struct instance)):
        emoji: "◎"
        color: rgb(207, 234, 140)
        name: "Accuracy"
        extra: 1

local function update(bindable: bindable struct, stat: Stat struct) -> textcomponent:
    return a_filled_stat_field("accuracy", a_percent({_stat}->current))
