local function load():
    save_component("stat:damage", a_stat_field(StatFieldBuilder struct instance)):
        emoji: "🗡"
        color: rgb(245, 65, 95)
        name: "Damage"
        extra: 0

local function update(bindable: bindable struct, stat: StatData struct) :: textcomponent:
    return a_filled_stat_field("damage", a_real({_stat}->bindable->value))

local function add(stat: StatData struct) :: Ratio struct:
    return Ratio struct instance:
        limit: 10