using script reflection

struct PrimaryAttack:
    order: integer = 1

local function add(stat: Stat struct) :: PrimaryAttack struct:
    return PrimaryAttack struct instance

local function load():
    save_component("stat:primary_attack", a_stat_field(StatFieldBuilder struct instance)):
        emoji: "›"
        color: rgb(100, 106, 250)
        name: "Primary Attack"
        extra: 5

local function update(bindable: bindable struct, stat: Stat struct) :: textcomponent:
    set {_type} to attack_type({_stat}->current)
    set_swing_animation({_stat}->item, {_type}->animation, {_type}->duration)
    return a_filled_stat_field("primary_attack", a_rank({_type}->id, white))