
using script reflection

struct SecondaryAttack:
    order: integer = 2

local function add(stat: Stat struct) -> SecondaryAttack struct:
    return SecondaryAttack struct instance

local function load():
    save_component("stat:secondary_attack", a_stat_field(StatFieldBuilder struct instance)):
        emoji: "›"
        color: rgb(40, 230, 95)
        name: "Secondary Attack"
        extra: 5

local function update(bindable: bindable struct, stat: Stat struct) -> textcomponent:
    set {_type} to attack_type({_stat}->current)
    set_consume_animation({_stat}->item, {_type}->animation, {_type}->duration)
    return a_filled_stat_field("secondary_attack", a_rank({_type}->id, white))
