
function on_damage(ctx: CombatContext struct):
    if {_ctx}->critical = true:
        fx_critical({_ctx}->hit)

    fx_blood({_ctx})

    play hurt animation on {_ctx}->victim
    set {_health} to wrapper({_ctx}->victim)->health_bar->bar->value
    if {_health}->value - ({_ctx}->damage / 10) < 0:
        on_death({_ctx}->victim)
        stop
    
    remove ({_ctx}->damage / 10) from {_health}'s bindable value
