using script reflection

function load_dev_state():
    set {-states::dev} to a_state_with("dev", function "start", function "tick", function "end")

local function start(event: string, machine: StateMachine struct):
    set {_wrapper} to {_machine}->context
    set {_player} to {_wrapper}->player
    set {_player}'s gamemode to creative
    transition_to({_player}, location(0, 20, 0))
    make {_player} fly

local function tick(machine: StateMachine struct):
    set {_wrapper} to {_machine}->context
    set {_player} to {_wrapper}->player
    send actionbar component colored_component("DEV MODE", rgb(50, 120, 230)) to {_player}

local function end(event: string, machine: StateMachine struct):
    set {_wrapper} to {_machine}->context
    set {_player} to {_wrapper}->player
    set {_player}'s gamemode to spectator

command /dev:
    permission: op
    trigger:
        trigger_event(wrapper(player)->machine, "dev")