struct Range:
    low: number = 0
    high: number = 1

function range(low: number, high: number) returns Range struct:
    return Range struct instance:
        low: {_low}
        high: {_high}

function range(high: number) returns Range struct:
    return Range struct instance:
        high: {_high}

function rnd(range: Range struct) returns number:
    return random number between {_range}->low and {_range}->high